### PR TITLE
Small code refactoring - to simplify things a little bit

### PR DESCRIPTION
**Pull request by alx3dev**
Here's what I did while I was trying to understand it. There's a lot more to do, but I am not that good with OpenGL like I am with ruby. I will spend some time on this to 'repack' code a little better, to add some methods.I would like to try to connect OpenSCAD  with this, for 3D model animation and printing simulation. Not that easy, but shouldn't be that hard with this already done.

### CODE REVIEW

**Comment by sinanislekdemir** [comment]
Thank you so much for the contribution! I hope you can find all you need in Blackbook, 

Gladly merging;

If you are looking for a bit more modern OpenGL alternative (but in Python) you can also check https://github.com/sinanislekdemir/payton (https://pypi.org/project/Payton/). It has a bit more features which maybe you may bring into Blackbook or might use in your projects;

**Comment by alx3dev** [comment]
I have hard time finding some reliable OpenGL tutorials. Even with great understanding of Ruby, i can't do much here... yet... I think I am just a step or two away of understanding it, so if you have any quality resource that I can read to actually understand how to move objects that I imported, don't hesitate to send me :)

**Comment by sinanislekdemir** [comment]
Speaking for the bare-metal OpenGL, there are two path you can choose.

1) Good old 1.1 Convention. which Blackbook follows. It's a fixed pipeline and has an impact on CPU.
2) Using shaders and getting the power of GPU. 

In both systems, moving an object is about matrices. 

Assuming that your UP direction is +Z. (Which I usually choose)

An objects initial position in the world can be described as:

Identity Matrix: 
```
[[1, 0, 0, 0],  # Side (usually left)
 [0, 1, 0, 0],  # Direction (where the object faces)
 [0, 0, 1, 0],  # Up
 [0, 0, 0, 1]]  # Position
```
When you want to move an object, you just change the position elements of the matrix.

When you want to rotate it, you create a rotation matrix and multiply objects matrix with it.

When your object has a parent object (like the weapon of a soldier), which will always follow it's parent, 
you need to think in relative coordinates. 

In that case, assume that Weapon's Matrix = WM and Soldier's Matrix = SM

WM = Identity Matrix (initial rest position)
SM = .... some position in space

While drawing the weapon, you need to calculate real-weapon-matrix. Which is RWM = WM x SM

That's why we have functions.rb https://github.com/sinanislekdemir/blackbook/blob/master/lib/BlackBook/functions.rb#L87

which include the main helper functions we have.

Reading through codes was helpful to me. Also there were the NeHe Tutorials but not sure if they still exists somewhere. They are not using the latest tech, but teaches well about basics.

In OpenGL shaders, you still use the same logics but this time coding on the GPU and it has some internal helper operators to help.

**Comment by sinanislekdemir** [comment]
https://github.com/Somsubhra/pyOpenGL-Samples/blob/master/cube.py

This is a very nice and clean example, in Python but the library commands should be the same because it's just OpenGL bindings.

**Pull request merged**
